version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "5050:3030"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
    networks:
     traefik:
       ipv4_address: 172.40.0.10

  app1:
      hostname: app1
      image: nightmareze1/nginx:v0.0.19
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app1.rule=Host(`app1.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.app1.entrypoints=web"
      networks:
       traefik:
        ipv4_address: 172.40.0.20

  app2:
      hostname: app2
      image: nightmareze1/nginx:v0.0.272
      labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app2.rule=Host(`app1.com`) && PathPrefix(`/shop`)"
      - "traefik.http.routers.app2.entrypoints=web"
      networks:
       traefik:
        ipv4_address: 172.40.0.21

networks:
 traefik:
  driver: bridge
  ipam:
    config:
    - subnet: 172.40.0.0/24
