[api]
  dashboard = true
  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"

[ping]

[log]
  level = "DEBUG"

[accessLog]

[providers]
  [providers.docker]
    exposedByDefault = false
  [providers.file]
    filename = "/etc/traefik/traefik.toml"

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]

[[tls.certificates]]
  certFile = "/mtls/cert.pem"
  keyFile = "/mtls/cert.pem"
