[api]
  dashboard = true
  insecure = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.websecure]
    address = ":443"
  [entryPoints.tcp]
    address = ":3030"
  [entryPoints.tcp1]
    address = ":3031"
  [entryPoints.tcp2]
    address = ":3032"
  [entryPoints.tcp3]
    address = ":3033"
  [entryPoints.tcp4]
    address = ":3034"
  [entryPoints.tcp5]
    address = ":3035"
  [entryPoints.tcp6]
    address = ":3036"
  [entryPoints.tcp7]
    address = ":3037"
  [entryPoints.tcp8]
    address = ":3038"
  [entryPoints.tcp9]
    address = ":3039"
 [entryPoints.tcp10]
    address = ":3040"

[ping]

[log]
  level = "INFO"

[accessLog]

[providers.ecs]
  clusters = ["test-dev"]
  exposedByDefault = false
  autoDiscoverClusters = false
  refreshSeconds = 10
  region = "us-west-2"
  accessKeyID = "asd"
  secretAccessKey = "bcasd"

[serversTransport]
  maxIdleConnsPerHost = 3072

[metrics]
  [metrics.prometheus]
    buckets = [0.1,0.3,1.2,5.0]
